# Generated by Django 3.0.5 on 2021-06-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normaluser', '0002_auto_20210611_0100'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
