# Generated by Django 3.0.5 on 2021-06-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normaluser', '0005_forgotpassworddb'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='category',
            field=models.CharField(choices=[('normal', 'Normal User'), ('admin', 'Administrator'), ('superadmin', 'Superadmin')], default='normal', max_length=50, null=True),
        ),
    ]
