# Generated by Django 3.0.5 on 2021-06-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normaluser', '0006_customuser_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.TextField(default='default.jpg', null=True),
        ),
    ]
